SELECT A.name
FROM Employee A
JOIN Employee B ON A.id=B.managerId
GROUP BY A.id
HAVING COUNT(B.id)>=5

-- 복습 풀이
SELECT B.NAME
FROM EMPLOYEE A
JOIN EMPLOYEE B
ON A.MANAGERID=B.ID
GROUP BY A.MANAGERID
HAVING COUNT(A.MANAGERID)>=5