-- 코드를 입력하세요
# 총주문량이 3,000보다 높으
# 주 성분이 과일
# 총주문량이 큰 순서대로 조회
SELECT A.FLAVOR
FROM FIRST_HALF A, ICECREAM_INFO B
WHERE A.FLAVOR=B.FLAVOR
AND TOTAL_ORDER>3000
AND INGREDIENT_TYPE='fruit_based'
ORDER BY TOTAL_ORDER DESC
