SELECT DISTINCT A.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Milk') AS A 
INNER JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Yogurt') AS B
ON A.CART_ID= B.CART_ID;

-- 복습 풀이
SELECT A.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Milk') A
JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Yogurt') B ON A.CART_ID=B.CART_ID
ORDER BY A.CART_ID