# 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
# 리뷰 작성일을 기준으로 오름차순/리뷰 텍스트를 기준으로 오름차순 정렬해주세요
WITH CTE AS (
    SELECT A.MEMBER_NAME,B.MEMBER_ID
    FROM MEMBER_PROFILE A
    JOIN REST_REVIEW B
    ON A.MEMBER_ID=B.MEMBER_ID
    GROUP BY B.MEMBER_ID
    HAVING COUNT(REVIEW_ID)=(
        SELECT COUNT(*) CNT
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    )
)

SELECT D.MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d')
FROM REST_REVIEW C
JOIN CTE D
ON C.MEMBER_ID=D.MEMBER_ID
ORDER BY REVIEW_DATE,REVIEW_TEXT