-- Python이나 C# 스킬을 가진 개발자의 정보를 조회
-- 개발자의 ID, 이메일, 이름, 성을 조회
-- ID를 기준으로 오름차순 정렬

-- SELECT DISTINCT A.ID, EMAIL,	FIRST_NAME,	LAST_NAME
SELECT DISTINCT DT.ID, DT.EMAIL, DT.FIRST_NAME,	DT.LAST_NAME
FROM
(
    SELECT *
    FROM DEVELOPERS A JOIN SKILLCODES B 
    WHERE A.SKILL_CODE & B.CODE = B.CODE
) DT
WHERE DT.NAME = 'Python' OR DT.NAME = 'C#'
ORDER BY A.ID ASC