-- DISTINCT 로 중복 데이터 제거해야함에 유의
SELECT YEAR(SALES_DATE) YEAR,MONTH(SALES_DATE) MONTH,COUNT(DISTINCT B.USER_ID) PURCHASED_USERS,
ROUND(COUNT(DISTINCT B.USER_ID)/(
    -- 스칼라 서브쿼리
    -- 2021년에 가입한 유저 수
    SELECT COUNT(*) TOTAL
    FROM USER_INFO 
    WHERE YEAR(JOINED)=2021
),1) PUCHASED_RATIO
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID=B.USER_ID
WHERE YEAR(JOINED)=2021
GROUP BY 1,2
ORDER BY 1,2