SELECT id,
    CASE
        WHEN id%2=0 THEN LAG(student) OVER (ORDER BY id)
        ELSE IFNULL(LEAD(student) OVER (ORDER BY id),student)
    END AS student
FROM Seat

-- 복습 풀이
SELECT ID,
CASE
WHEN ID%2!=0 THEN IFNULL(LEAD(STUDENT,1) OVER (ORDER BY ID),STUDENT)
ELSE LAG(STUDENT,1) OVER (ORDER BY ID)
END STUDENT
FROM SEAT