WITH CTE AS (
    SELECT ID,SIZE_OF_COLONY,PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME
    FROM ECOLI_DATA 
)

SELECT CTE.ID,
CASE
    WHEN CTE.COLONY_NAME<=0.25 THEN 'CRITICAL'
    WHEN CTE.COLONY_NAME<=0.50 THEN 'HIGH'
    WHEN CTE.COLONY_NAME<=0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM CTE
ORDER BY ID