WITH RECURSIVE AR AS
(
    SELECT ID,PARENT_ID,1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID,A.PARENT_ID,AR.GEN+1 AS GEN
    FROM ECOLI_DATA A
    JOIN AR ON A.PARENT_ID=AR.ID
)
SELECT COUNT(ARB.GEN) AS COUNT,ARB.GEN AS GENERATION
FROM AR
RIGHT JOIN AR ARB ON AR.PARENT_ID=ARB.ID
WHERE AR.ID IS NULL
GROUP BY ARB.GEN
ORDER BY ARB.GEN ASC