WITH CTE AS
(
    SELECT A.EMP_NO,EMP_NAME,AVG(SCORE) SCORE_AVG,SAL
    FROM HR_EMPLOYEES A
    JOIN HR_GRADE B
    ON A.EMP_NO=B.EMP_NO
    GROUP BY B.EMP_NO
)

SELECT CTE.EMP_NO,CTE.EMP_NAME,
(
    CASE
    WHEN CTE.SCORE_AVG>=96 THEN 'S'
    WHEN CTE.SCORE_AVG>=90 THEN 'A'
    WHEN CTE.SCORE_AVG>=80 THEN 'B'
    ELSE 'C'
    END
) GRADE,
(
    CASE
    WHEN CTE.SCORE_AVG>=96 THEN CTE.SAL*0.20
    WHEN CTE.SCORE_AVG>=90 THEN CTE.SAL*0.15
    WHEN CTE.SCORE_AVG>=80 THEN CTE.SAL*0.10
    ELSE 0
    END
) BONUS
FROM CTE
ORDER BY CTE.EMP_NO