-- 정렬 조건에 유의
SELECT ROUTE,CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE,CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) DESC;

-- 복습 풀이
SELECT 
ROUTE,
CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') TOTAL_DISTANCE,
CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE
-- 정렬은 컬럼(문자열)이 아닌 실제 값(숫자)로 함에 유의
ORDER BY SUM(D_BETWEEN_DIST) DESC