# 2022년 3월
# 판매 날짜, 상품ID, 유저ID, 판매량을 출력
# 판매일을 기준으로 오름차순 정렬/상품 ID를 기준으로 오름차순/유저 ID를 기준으로 오름차순 정렬
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-03'
UNION
-- 처음부터 없던 컬럼은 NULL로 채움
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID,NULL USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE  
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-03'
ORDER BY SALES_DATE,PRODUCT_ID,USER_ID