# 고양이를 개보다 먼저 조회
SELECT ANIMAL_TYPE,COUNT(ANIMAL_ID)
FROM ANIMAL_INS 
WHERE ANIMAL_TYPE='Cat' OR ANIMAL_TYPE='Dog'
GROUP BY ANIMAL_TYPE
ORDER BY 
    CASE 
        WHEN ANIMAL_TYPE='Cat' THEN 1
        WHEN ANIMAL_TYPE='Dog' THEN 2
    END