-- 코드를 입력하세요
# 생일이 3월인 여성 회원
# 전화번호가 NULL인 경우는 출력대상에서 제외
# 회원ID를 기준으로 오름차순 정렬
SELECT MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE GENDER='W'
AND MONTH(DATE_OF_BIRTH)='3'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID
